NAME: 'CIFAR10.res32.200epoch'
OUTPUT_DIR: './output/cifar10/0.01/64/LDAM'
SHOW_STEP: 100
SAVE_STEP: 5
VALID_STEP: 1
INPUT_SIZE: (32, 32)
COLOR_SPACE: 'RGB'
CPU_MODE: False

DATASET:
  DATASET: 'IMBALANCECIFAR10'
  IMBALANCECIFAR:
    RATIO: 0.01

BACKBONE:
  TYPE: 'res32_cifar'

MODULE:
  TYPE: 'GAP'

CLASSIFIER:
  TYPE: 'FCNorm'
  BIAS: True

LOSS:
  LOSS_TYPE: 'LDAMLoss'

TRAIN:
  BATCH_SIZE: 64
  MAX_EPOCH: 200
  NUM_WORKERS: 4
  OPTIMIZER:
    TYPE: 'SGD'
    BASE_LR: 0.1
    MOMENTUM: 0.9
    WEIGHT_DECAY: 2e-4
  LR_SCHEDULER:
    TYPE: 'warmup'
    LR_STEP: [120, 160]
    LR_FACTOR: 0.01
    WARM_EPOCH: 5
  TENSORBOARD:
    ENABLE: True
  SAMPLER:
    TYPE: 'default'
    # TYPE: "weighted sampler"
    # WEIGHTED_SAMPLER:
    #   TYPE: "reverse"

TRANSFORMS:
  TRAIN_TRANSFORMS: ('random_crop', 'random_horizontal_flip')
  TEST_TRANSFORMS: ()

TEST:
  BATCH_SIZE: 128
  NUM_WORKERS: 4
  MODEL_FILE: 'best_model.pth'
