NAME: 'Baseline.iNaturalist2017.res50.90epoch'
OUTPUT_DIR: './output/iNat17_90_baseline'
SHOW_STEP: 500
SAVE_STEP: 5
VALID_STEP: 1
INPUT_SIZE: (224, 224)
COLOR_SPACE: 'RGB'
CPU_MODE: False

DATASET:
  DATASET: 'iNaturalist'
  DATA_TYPE: 'jpg'
  TRAIN_JSON: './jsons/converted_train2017.json'
  VALID_JSON: './jsons/converted_val2017.json'

BACKBONE:
  TYPE: 'res50'

MODULE:
  TYPE: 'GAP'

LOSS:
  LOSS_TYPE: 'CrossEntropy'
  RATIO: 1.1

CLASSIFIER:
  TYPE: 'FC'
  BIAS: True
  
TRAIN:
  BATCH_SIZE: 128
  MAX_EPOCH: 90
  NUM_WORKERS: 16
  COMBINER:
    TYPE: 'default'
  TENSORBOARD:
    ENABLE: False
  SAMPLER:
    TYPE: 'default'
    DUAL_SAMPLER:
      ENABLE: False
      TYPE: 'reverse'
  OPTIMIZER:
    TYPE: 'SGD'
    BASE_LR: 0.05
    MOMENTUM: 0.9
    WEIGHT_DECAY: 1e-4
  LR_SCHEDULER:
    TYPE: 'multistep'
    LR_STEP: [55, 75, 85]
    LR_FACTOR: 0.1

TRANSFORMS:
  TRAIN_TRANSFORMS: ("random_resized_crop", "random_horizontal_flip")
  TEST_TRANSFORMS: ("shorter_resize_for_crop", "center_crop")

TEST:
  BATCH_SIZE: 128
  NUM_WORKERS: 16
  MODEL_FILE: 'best_model.pth'

